### ISSUE TITLE
Why is there no support for H.265 videos??

### ISSUE THREAD

**Issue by 7Codez** [vivictorg/vivict#29]
We need support for H.265 (HEVC) videos

**Comment by grusell** [comment]
Which browser are you using? If you browser can play the file it should normally be playable in vivict.

**Comment by 7Codez** [comment]
H.265 12-bit (x265)
H.265 10-bit NVENC

Can these types be opened in your app?

**Comment by 7Codez** [comment]
You're right, my videos don't open in (H.265 12-bit (x265)) and (H.265 10-bit NVENC) in my browsers (no picture. It has sound).

I tried the desktop version (Vivict++) and it worked great and opened (H.265 12-bit (x265)) and (H.265 10-bit NVENC).
vivictpp > v0.3.0 prerelase > Worked :))))))))))))))))))))))))

Thank you, wonderful programmer. Searching the web, there are no other applications as efficient as yours.

**Comment by 7Codez** [comment]
Has this Hindu taken a copy of the application that does not work? What is the status of your app ownership? Is it stolen or do you own it?

https://www.youtube.com/watch?v=ZAq3I8VduFg&t=8s

**Comment by janderssonse** [comment]
The LICENSE tells you the term of the code and how you can use it and that tells that ownership, and also what you can do (and not do with it). Split screen video applications, yes there are commercial ones, and open source ones pick your choice. But, please, don't impl, y just because you found a link to one of them that it would be stolen.  To be honest I think it is really rude to imply that an Open Source project would have stolen the code without a single line to back it up, really.
